"""Target-list exports in the formats operators load.

* Magellan observing catalog (16 whitespace-separated fields, lco.cl "Observing Catalogs
  Format"): ref, name (no whitespace), RA, Dec, equinox, PM RA (s/yr), PM Dec ("/yr),
  rotator offset angle, rotator mode (OFF|EQU|HRZ|GRV), guide probe 1 RA/Dec/equinox, guide
  probe 2 RA/Dec/equinox, observation epoch.
* Keck starlist (name padded to 15 characters, RA "hh mm ss.ss", Dec "+dd mm ss.s", equinox,
  then optional key=value pairs such as rotmode/rotdest).

Guide stars are left as zeros (the operator picks them) unless given in `Target.extra`.
"""

from __future__ import annotations

from typing import Iterable, List, Optional

from obsassist.astro.ephem import fmt_dec, fmt_ra
from obsassist.targets import Program, Target


def _name(t: Target) -> str:
    return "".join(ch if ch.isalnum() or ch in "+-_." else "_" for ch in t.name)


def magellan_catalog(program: Program, targets: Optional[Iterable[Target]] = None, instrument: str = "MIKE") -> str:
    """Rotator: MIKE does not rotate (gravity-invariant) -> OFF; slit spectrographs use EQU with the
    target PA when fixed, else HRZ (parallactic)."""
    lines: List[str] = [
        f"# {program.name} - Magellan catalog ({instrument}), generated by obsassist",
        '# ref name RA Dec equinox pmRA(s/yr) pmDec("/yr) rot_angle rot_mode '
        "gp1_RA gp1_Dec gp1_eq gp2_RA gp2_Dec gp2_eq epoch",
    ]
    for k, t in enumerate(targets if targets is not None else program.targets, start=1):
        if instrument.upper() == "MIKE":
            rot, mode = 0.0, "OFF"
        elif t.pa is not None:
            rot, mode = float(t.pa), "EQU"
        else:
            rot, mode = 0.0, "HRZ"
        lines.append(
            f"{k:3d} {_name(t):20s} {fmt_ra(t.ra)} {fmt_dec(t.dec)} 2000.0 0.000 0.00 "
            f"{rot:6.1f} {mode} 00:00:00.00 +00:00:00.0 2000.0 00:00:00.00 +00:00:00.0 2000.0 0.0"
        )
    return "\n".join(lines) + "\n"


def keck_starlist(program: Program, targets: Optional[Iterable[Target]] = None) -> str:
    out: List[str] = [f"# {program.name} - Keck starlist, generated by obsassist"]
    for t in targets if targets is not None else program.targets:
        ra = fmt_ra(t.ra).replace(":", " ")  # "hh mm ss.ss" (11 characters)
        dec = fmt_dec(t.dec).replace(":", " ")  # "+dd mm ss.s" (11 characters)
        extra = f" rotmode=pa rotdest={t.pa:.1f}" if t.pa is not None else " rotmode=vertical"
        out.append(f"{_name(t)[:15]:15s} {ra} {dec} 2000.0{extra}")
    return "\n".join(out) + "\n"
